# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: online_hmm.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='online_hmm.proto',
  package='hello',
  serialized_pb='\n\x10online_hmm.proto\x12\x05hello\"J\n\nRealMatrix\x12\x10\n\x08num_rows\x18\x01 \x02(\x05\x12\x10\n\x08num_cols\x18\x02 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x01\x12\n\n\x02id\x18\x04 \x01(\t\"&\n\nTransition\x12\x0c\n\x04\x66rom\x18\x01 \x02(\x05\x12\n\n\x02to\x18\x02 \x02(\x05\"\x87\x01\n\x16MotionModelRestriction\x12\x17\n\x0fmotion_model_id\x18\x01 \x01(\t\x12\x39\n\x1e\x66orbiddeden_motion_transitions\x18\x02 \x03(\x0b\x32\x11.hello.Transition\x12\x19\n\x11non_motion_states\x18\x03 \x03(\x05\"\xab\x03\n\x10\x41lphabetHmmPrior\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\toutput_id\x18\x02 \x01(\x0e\x32\x0f.hello.OutputId\x12\x18\n\x10\x64\x61te_created_utc\x18\x03 \x01(\x03\x12\x18\n\x10\x64\x61te_updated_utc\x18\x04 \x01(\x03\x12\x39\n\x1elog_state_transition_numerator\x18\x05 \x01(\x0b\x32\x11.hello.RealMatrix\x12:\n\x1flog_observation_model_numerator\x18\x06 \x03(\x0b\x32\x11.hello.RealMatrix\x12!\n\x19log_observation_model_ids\x18\x07 \x03(\t\x12\x17\n\x0flog_denominator\x18\x08 \x03(\x01\x12\n\n\x02pi\x18\t \x03(\x01\x12\x12\n\nend_states\x18\n \x03(\x05\x12\x1f\n\x17minimum_state_durations\x18\x0b \x03(\x05\x12?\n\x18motion_model_restriction\x18\x0c \x01(\x0b\x32\x1d.hello.MotionModelRestriction\"e\n\x15\x41lphabetHmmScratchPad\x12\x1d\n\x15last_date_updated_utc\x18\x01 \x01(\x03\x12-\n\x0cmodel_deltas\x18\x02 \x03(\x0b\x32\x17.hello.AlphabetHmmPrior\"?\n\x14\x41lphabetHmmUserModel\x12\'\n\x06models\x18\x01 \x03(\x0b\x32\x17.hello.AlphabetHmmPrior*\x1e\n\x08OutputId\x12\t\n\x05SLEEP\x10\x00\x12\x07\n\x03\x42\x45\x44\x10\x01\x42\x33\n com.hello.suripu.api.datascienceB\x0fOnlineHmmProtos')

_OUTPUTID = _descriptor.EnumDescriptor(
  name='OutputId',
  full_name='hello.OutputId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SLEEP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=879,
  serialized_end=909,
)

OutputId = enum_type_wrapper.EnumTypeWrapper(_OUTPUTID)
SLEEP = 0
BED = 1



_REALMATRIX = _descriptor.Descriptor(
  name='RealMatrix',
  full_name='hello.RealMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_rows', full_name='hello.RealMatrix.num_rows', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_cols', full_name='hello.RealMatrix.num_cols', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='hello.RealMatrix.data', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='hello.RealMatrix.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=101,
)


_TRANSITION = _descriptor.Descriptor(
  name='Transition',
  full_name='hello.Transition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='hello.Transition.from', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='hello.Transition.to', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=141,
)


_MOTIONMODELRESTRICTION = _descriptor.Descriptor(
  name='MotionModelRestriction',
  full_name='hello.MotionModelRestriction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motion_model_id', full_name='hello.MotionModelRestriction.motion_model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forbiddeden_motion_transitions', full_name='hello.MotionModelRestriction.forbiddeden_motion_transitions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='non_motion_states', full_name='hello.MotionModelRestriction.non_motion_states', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=279,
)


_ALPHABETHMMPRIOR = _descriptor.Descriptor(
  name='AlphabetHmmPrior',
  full_name='hello.AlphabetHmmPrior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hello.AlphabetHmmPrior.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_id', full_name='hello.AlphabetHmmPrior.output_id', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_created_utc', full_name='hello.AlphabetHmmPrior.date_created_utc', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_updated_utc', full_name='hello.AlphabetHmmPrior.date_updated_utc', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_state_transition_numerator', full_name='hello.AlphabetHmmPrior.log_state_transition_numerator', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_observation_model_numerator', full_name='hello.AlphabetHmmPrior.log_observation_model_numerator', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_observation_model_ids', full_name='hello.AlphabetHmmPrior.log_observation_model_ids', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_denominator', full_name='hello.AlphabetHmmPrior.log_denominator', index=7,
      number=8, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pi', full_name='hello.AlphabetHmmPrior.pi', index=8,
      number=9, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_states', full_name='hello.AlphabetHmmPrior.end_states', index=9,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum_state_durations', full_name='hello.AlphabetHmmPrior.minimum_state_durations', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motion_model_restriction', full_name='hello.AlphabetHmmPrior.motion_model_restriction', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=282,
  serialized_end=709,
)


_ALPHABETHMMSCRATCHPAD = _descriptor.Descriptor(
  name='AlphabetHmmScratchPad',
  full_name='hello.AlphabetHmmScratchPad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_date_updated_utc', full_name='hello.AlphabetHmmScratchPad.last_date_updated_utc', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_deltas', full_name='hello.AlphabetHmmScratchPad.model_deltas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=711,
  serialized_end=812,
)


_ALPHABETHMMUSERMODEL = _descriptor.Descriptor(
  name='AlphabetHmmUserModel',
  full_name='hello.AlphabetHmmUserModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='hello.AlphabetHmmUserModel.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=814,
  serialized_end=877,
)

_MOTIONMODELRESTRICTION.fields_by_name['forbiddeden_motion_transitions'].message_type = _TRANSITION
_ALPHABETHMMPRIOR.fields_by_name['output_id'].enum_type = _OUTPUTID
_ALPHABETHMMPRIOR.fields_by_name['log_state_transition_numerator'].message_type = _REALMATRIX
_ALPHABETHMMPRIOR.fields_by_name['log_observation_model_numerator'].message_type = _REALMATRIX
_ALPHABETHMMPRIOR.fields_by_name['motion_model_restriction'].message_type = _MOTIONMODELRESTRICTION
_ALPHABETHMMSCRATCHPAD.fields_by_name['model_deltas'].message_type = _ALPHABETHMMPRIOR
_ALPHABETHMMUSERMODEL.fields_by_name['models'].message_type = _ALPHABETHMMPRIOR
DESCRIPTOR.message_types_by_name['RealMatrix'] = _REALMATRIX
DESCRIPTOR.message_types_by_name['Transition'] = _TRANSITION
DESCRIPTOR.message_types_by_name['MotionModelRestriction'] = _MOTIONMODELRESTRICTION
DESCRIPTOR.message_types_by_name['AlphabetHmmPrior'] = _ALPHABETHMMPRIOR
DESCRIPTOR.message_types_by_name['AlphabetHmmScratchPad'] = _ALPHABETHMMSCRATCHPAD
DESCRIPTOR.message_types_by_name['AlphabetHmmUserModel'] = _ALPHABETHMMUSERMODEL

class RealMatrix(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REALMATRIX

  # @@protoc_insertion_point(class_scope:hello.RealMatrix)

class Transition(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSITION

  # @@protoc_insertion_point(class_scope:hello.Transition)

class MotionModelRestriction(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOTIONMODELRESTRICTION

  # @@protoc_insertion_point(class_scope:hello.MotionModelRestriction)

class AlphabetHmmPrior(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALPHABETHMMPRIOR

  # @@protoc_insertion_point(class_scope:hello.AlphabetHmmPrior)

class AlphabetHmmScratchPad(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALPHABETHMMSCRATCHPAD

  # @@protoc_insertion_point(class_scope:hello.AlphabetHmmScratchPad)

class AlphabetHmmUserModel(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALPHABETHMMUSERMODEL

  # @@protoc_insertion_point(class_scope:hello.AlphabetHmmUserModel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n com.hello.suripu.api.datascienceB\017OnlineHmmProtos')
# @@protoc_insertion_point(module_scope)
