# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beta_binomial.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='beta_binomial.proto',
  package='hello',
  serialized_pb=_b('\n\x13\x62\x65ta_binomial.proto\x12\x05hello\"+\n\x0c\x42\x65taCondProb\x12\r\n\x05\x61lpha\x18\x01 \x02(\x01\x12\x0c\n\x04\x62\x65ta\x18\x02 \x02(\x01\"T\n\tCondProbs\x12\x10\n\x08model_id\x18\x01 \x02(\t\x12\x11\n\toutput_id\x18\x02 \x02(\t\x12\"\n\x05probs\x18\x03 \x03(\x0b\x32\x13.hello.BetaCondProb\"9\n\x11MultipleCondProbs\x12$\n\ncond_probs\x18\x01 \x03(\x0b\x32\x10.hello.CondProbsB6\n com.hello.suripu.api.datascienceB\x12\x42\x65taBinomialProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BETACONDPROB = _descriptor.Descriptor(
  name='BetaCondProb',
  full_name='hello.BetaCondProb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='hello.BetaCondProb.alpha', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta', full_name='hello.BetaCondProb.beta', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)


_CONDPROBS = _descriptor.Descriptor(
  name='CondProbs',
  full_name='hello.CondProbs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='hello.CondProbs.model_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_id', full_name='hello.CondProbs.output_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='probs', full_name='hello.CondProbs.probs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=159,
)


_MULTIPLECONDPROBS = _descriptor.Descriptor(
  name='MultipleCondProbs',
  full_name='hello.MultipleCondProbs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cond_probs', full_name='hello.MultipleCondProbs.cond_probs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=218,
)

_CONDPROBS.fields_by_name['probs'].message_type = _BETACONDPROB
_MULTIPLECONDPROBS.fields_by_name['cond_probs'].message_type = _CONDPROBS
DESCRIPTOR.message_types_by_name['BetaCondProb'] = _BETACONDPROB
DESCRIPTOR.message_types_by_name['CondProbs'] = _CONDPROBS
DESCRIPTOR.message_types_by_name['MultipleCondProbs'] = _MULTIPLECONDPROBS

BetaCondProb = _reflection.GeneratedProtocolMessageType('BetaCondProb', (_message.Message,), dict(
  DESCRIPTOR = _BETACONDPROB,
  __module__ = 'beta_binomial_pb2'
  # @@protoc_insertion_point(class_scope:hello.BetaCondProb)
  ))
_sym_db.RegisterMessage(BetaCondProb)

CondProbs = _reflection.GeneratedProtocolMessageType('CondProbs', (_message.Message,), dict(
  DESCRIPTOR = _CONDPROBS,
  __module__ = 'beta_binomial_pb2'
  # @@protoc_insertion_point(class_scope:hello.CondProbs)
  ))
_sym_db.RegisterMessage(CondProbs)

MultipleCondProbs = _reflection.GeneratedProtocolMessageType('MultipleCondProbs', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLECONDPROBS,
  __module__ = 'beta_binomial_pb2'
  # @@protoc_insertion_point(class_scope:hello.MultipleCondProbs)
  ))
_sym_db.RegisterMessage(MultipleCondProbs)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.hello.suripu.api.datascienceB\022BetaBinomialProtos'))
# @@protoc_insertion_point(module_scope)
